# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":arrow_up:"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":arrow_up:"
