name: Resolve dream2nix dependencies

on:
  push:
    paths:
      - 'package-lock.json'

jobs:
  resolve:
    name: Resolve dream2nix dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Resolve dream2nix dependencies
        run: nix run .#flakeaway.resolve

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Resolve dream2nix dependencies :pushpin:'
          default_author: github_actions
